version: "3"

services:
    redis:
        container_name: dc-redis
        image: redis:alpine
        networks:
            - nw-redis
        ports:
            - 6379:6379
        restart: always
        tty: true
        volumes:
            - ./redis-data:/data

networks:
    nw-redis:
        driver: bridge
